# Generated by Django 4.1.1 on 2022-09-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('first_section_title', models.CharField(max_length=255, verbose_name='título')),
                ('first_section_highlight', models.CharField(max_length=255, verbose_name='destacado')),
                ('first_section_description', models.TextField(blank=True, verbose_name='descripción')),
                ('first_section_main_button', models.CharField(max_length=255, verbose_name='botón principal')),
                ('first_section_main_button_url', models.URLField(verbose_name='url del botón principal')),
                ('first_section_secondary_button', models.CharField(max_length=255, verbose_name='botón secundario')),
                ('first_section_secondary_button_url', models.URLField(verbose_name='url del botón secundario')),
                ('first_section_image', models.ImageField(upload_to='home', verbose_name='imagen')),
                ('first_section_subtitle', models.CharField(max_length=255, verbose_name='subtítulo')),
                ('first_section_subtitle_description', models.TextField(blank=True, verbose_name='descripción')),
                ('first_section_link', models.URLField(verbose_name='enlace')),
                ('first_section_link_text', models.CharField(max_length=255, verbose_name='texto del enlace')),
                ('second_section_title', models.CharField(max_length=255, verbose_name='título')),
                ('second_section_highlight', models.CharField(max_length=255, verbose_name='destacado')),
                ('second_section_description', models.TextField(blank=True, verbose_name='descripción')),
                ('second_section_main_button', models.CharField(max_length=255, verbose_name='botón principal')),
                ('second_section_main_button_url', models.URLField(verbose_name='url del botón principal')),
                ('third_section_title', models.CharField(max_length=255, verbose_name='título')),
                ('third_section_highlight', models.CharField(max_length=255, verbose_name='destacado')),
                ('third_section_description', models.TextField(blank=True, verbose_name='descripción')),
                ('third_section_main_button', models.CharField(max_length=255, verbose_name='botón principal')),
                ('third_section_main_button_url', models.URLField(verbose_name='url del botón principal')),
                ('fourth_section_card_1_image', models.ImageField(upload_to='home', verbose_name='imagen')),
                ('fourth_section_card_1_title', models.CharField(max_length=255, verbose_name='título')),
                ('fourth_section_card_1_description', models.TextField(blank=True, verbose_name='descripción')),
                ('fourth_section_card_1_button', models.CharField(max_length=255, verbose_name='botón')),
                ('fourth_section_card_1_button_url', models.URLField(verbose_name='url del botón')),
                ('fourth_section_card_2_image', models.ImageField(upload_to='home', verbose_name='imagen')),
                ('fourth_section_card_2_title', models.CharField(max_length=255, verbose_name='título')),
                ('fourth_section_card_2_description', models.TextField(blank=True, verbose_name='descripción')),
                ('fourth_section_card_2_button', models.CharField(max_length=255, verbose_name='botón')),
                ('fourth_section_card_2_button_url', models.URLField(verbose_name='url del botón')),
                ('fifth_section_title', models.CharField(max_length=255, verbose_name='título')),
                ('fifth_section_words', models.TextField(blank=True, verbose_name='palabras')),
                ('fifth_section_description', models.TextField(blank=True, verbose_name='descripción')),
                ('fifth_section_button', models.CharField(max_length=255, verbose_name='botón')),
                ('fifth_section_button_url', models.URLField(verbose_name='url del botón')),
            ],
            options={
                'verbose_name_plural': 'home',
            },
        ),
    ]
