# Generated by Django 3.2.16 on 2023-01-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Barra de Navegación',
                'verbose_name_plural': 'Barra de Navegación',
            },
        ),
        migrations.AlterModelOptions(
            name='enviosnacionalesbeneficios',
            options={'verbose_name': 'Modalidades', 'verbose_name_plural': 'Modalidades'},
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='primera_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='primera_seccion_alt_imagen_movil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen móvil'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='primera_seccion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='centro de ayuda', verbose_name='imagen de fondo'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='primera_seccion_imagen_movil',
            field=models.ImageField(blank=True, null=True, upload_to='centro de ayuda', verbose_name='imagen móvil'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='primera_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='primera_seccion_titulo_imagen_movil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen móvil'),
        ),
        migrations.AddField(
            model_name='enviosnacionalesbeneficios',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='envios nacionales', verbose_name='ícono'),
        ),
        migrations.AddField(
            model_name='sucursaltipo',
            name='estacionamiento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='estacionamiento'),
        ),
        migrations.AlterField(
            model_name='about',
            name='cuarta_seccion_boton_principal_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuarta_url_boton_principal_about', to='cms.url', verbose_name='url del botón principal'),
        ),
        migrations.AlterField(
            model_name='about',
            name='cuarta_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_url_boton_secundario_cuarta_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='about',
            name='primera_seccion_boton_principal_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primera_url_boton_principal_about', to='cms.url', verbose_name='url del botón principal'),
        ),
        migrations.AlterField(
            model_name='about',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='about',
            name='quinta_seccion_boton_principal_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quinta_url_boton_principal_about', to='cms.url', verbose_name='url del botón principal'),
        ),
        migrations.AlterField(
            model_name='about',
            name='quinta_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_url_boton_secundario_quinta_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='about',
            name='tercera_seccion_boton_principal_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tercera_url_boton_principal_about', to='cms.url', verbose_name='url del botón principal'),
        ),
        migrations.AlterField(
            model_name='about',
            name='tercera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_url_boton_secundario_tercera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='accion',
            name='boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_accion', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='accionria',
            name='boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_accion_ria', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='segunda_seccion_url_primer_boton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_primer_boton_articulo', to='cms.url', verbose_name='url del primer botón'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='segunda_seccion_url_segundo_boton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_segundo_boton_articulo', to='cms.url', verbose_name='url del segundo botón'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_primer_boton', to='cms.url', verbose_name='url del primer botón'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='segundo_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_segundo_boton', to='cms.url', verbose_name='url del segundo botón'),
        ),
        migrations.AlterField(
            model_name='boton',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_cotizador', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='primera_seccion_boton_principal_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primera_url_boton_principal_centro_de_ayuda', to='cms.url', verbose_name='url del botón principal'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centro_de_ayuda_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='segunda_seccion_boton_principal_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segunda_url_boton_principal_centro_de_ayuda', to='cms.url', verbose_name='url del botón principal'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='segunda_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centro_de_ayuda_url_boton_secundario_segunda_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='centrodeayudabeneficio',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_centro_de_ayuda_beneficio', to='cms.url', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='cuarta_seccion_tarjeta_1_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_tarjeta_1_contactanos', to='cms.url', verbose_name='url del botón tarjeta 1'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='cuarta_seccion_tarjeta_2_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_tarjeta_2_contactanos', to='cms.url', verbose_name='url del botón tarjeta 2'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='primera_seccion_boton_principal_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primera_url_boton_principal_contactanos', to='cms.url', verbose_name='url del botón principal'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactanos_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='segunda_seccion_url_whatsapp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_whatsapp', to='cms.url', verbose_name='url de whatsapp'),
        ),
        migrations.AlterField(
            model_name='cotizador',
            name='tercer_bloque_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tercer_bloque_url_boton_cotizador', to='cms.url', verbose_name='tercer bloque url del botón'),
        ),
        migrations.AlterField(
            model_name='covid',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covid_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='covid',
            name='primera_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_covid', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='dhl',
            name='cuarta_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dhl_url_boton_secundario_cuarta_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='dhl',
            name='cuarta_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuarta_url_boton_principal_dhl', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='dhl',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dhl_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='dhl',
            name='primera_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primera_url_boton_principal_dhl', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cuarta_seccion_primer_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_primer_boton_empresas', to='cms.url', verbose_name='url del primer botón'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cuarta_seccion_segundo_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_segundo_boton_empresas', to='cms.url', verbose_name='url del segundo botón'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='primera_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primera_url_boton_empresas', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='quinta_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quinta_url_boton_empresas', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='tercera_seccion_enlace_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_enlace_empresas', to='cms.url', verbose_name='url del enlace'),
        ),
        migrations.AlterField(
            model_name='enviosinternacionales',
            name='cuarta_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internacionales_url_boton_secundario_cuarta_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='enviosinternacionales',
            name='cuarta_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuarta_url_boton_envios_internacionales', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='enviosinternacionales',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internacionales_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='enviosinternacionales',
            name='primera_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primera_url_boton_envios_internacionales', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='enviosinternacionales',
            name='quinta_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quinta_url_boton_envios_internacionales', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='enviosnacionales',
            name='cuarta_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nacionales_url_boton_secundario_cuarta_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='enviosnacionales',
            name='cuarta_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuarta_url_boton_envios_nacionales', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='enviosnacionales',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nacionales_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='enviosnacionales',
            name='primera_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primera_url_boton_envios_nacionales', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='enviosnacionales',
            name='tercera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nacionales_url_boton_secundario_tercera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='enviosnacionales',
            name='tercera_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tercera_url_boton_envios_nacionales', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='enviosnacionalesbeneficios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='envios nacionales', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cuarta_seccion_tarjeta_1_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_tarjeta_1', to='cms.url', verbose_name='url del botón tarjeta 1'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cuarta_seccion_tarjeta_2_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_tarjeta_2', to='cms.url', verbose_name='url del botón tarjeta 2'),
        ),
        migrations.AlterField(
            model_name='home',
            name='primera_seccion_boton_principal_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_principal', to='cms.url', verbose_name='url del botón principal'),
        ),
        migrations.AlterField(
            model_name='home',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_secundario', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='home',
            name='quinta_seccion_app_store_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quinta_url_boton_principal', to='cms.url', verbose_name='enlace playstore'),
        ),
        migrations.AlterField(
            model_name='home',
            name='quinta_seccion_google_play_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_secundario_quinta_seccion', to='cms.url', verbose_name='enlace appstore'),
        ),
        migrations.AlterField(
            model_name='home',
            name='segunda_seccion_boton_principal_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segunda_url_boton_principal', to='cms.url', verbose_name='url del botón principal'),
        ),
        migrations.AlterField(
            model_name='home',
            name='segunda_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_secundario_segunda_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='home',
            name='tercera_seccion_boton_principal_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tercera_url_boton_principal', to='cms.url', verbose_name='url del botón principal'),
        ),
        migrations.AlterField(
            model_name='home',
            name='tercera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_secundario_tercera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='login',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='login',
            name='primera_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primera_url_boton_login', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='login',
            name='segunda_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_url_boton_secundario_segunda_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='login',
            name='segunda_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_login_segunda_seccion', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='miprimerenvio',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mi_primer_envio_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='miprimerenvio',
            name='primera_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_mi_primer_envio', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='miprimerenviostep',
            name='boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_mi_primer_envio_step', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='mypymes',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mypymes_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='mypymes',
            name='primera_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primera_url_boton_mypymes', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='mypymes',
            name='septima_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='septima_url_boton_mypymes', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='mypymes',
            name='sexta_seccion_primer_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_primer_boton_mypymes', to='cms.url', verbose_name='url del primer botón'),
        ),
        migrations.AlterField(
            model_name='mypymes',
            name='sexta_seccion_segundo_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_segundo_boton_mypymes', to='cms.url', verbose_name='url del segundo botón'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='cms.preguntascategoria', verbose_name='Preguntas'),
        ),
        migrations.AlterField(
            model_name='preguntasfrecuentes',
            name='tercera_seccion_url_primer_bloque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_tercera_seccion_primer_bloque', to='cms.url', verbose_name='url botón primer bloque'),
        ),
        migrations.AlterField(
            model_name='preguntasfrecuentes',
            name='tercera_seccion_url_segundo_bloque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_tercera_seccion_segundo_bloque', to='cms.url', verbose_name='url botón segundo bloque'),
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='primera_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primera_url_boton_reclamos', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='tercera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_url_boton_secundario_tercera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='tercera_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_url_boton_tercera_seccion', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='recomendaciones',
            name='recomendacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones', to='cms.recomendacionescategoria', verbose_name='Recomendaciones'),
        ),
        migrations.AlterField(
            model_name='recomendacionesembalaje',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones_embalaje_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='recomendacionesembalaje',
            name='primera_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_recomendaciones_embalaje', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='redsocial',
            name='boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_red_social', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cuarta_seccion_tarjeta_1_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_tarjeta_1_registro', to='cms.url', verbose_name='url del botón tarjeta 1'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cuarta_seccion_tarjeta_2_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_tarjeta_2_registro', to='cms.url', verbose_name='url del botón tarjeta 2'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='primera_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primera_url_boton_registro', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='ria',
            name='cuarta_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ria_url_boton_secundario_cuarta_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='ria',
            name='cuarta_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuarta_url_boton_principal_ria', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='ria',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ria_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='ria',
            name='primera_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primera_url_boton_principal_ria', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='cuarta_seccion_app_store_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuarta_url_boton_principal', to='cms.url', verbose_name='enlace playstore'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='cuarta_seccion_google_play_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_secundario_cuarta_seccion', to='cms.url', verbose_name='enlace appstore'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='tercera_seccion_tarjeta_1_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_1_seguimiento', to='cms.url', verbose_name='url del botón 1'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='tercera_seccion_tarjeta_2_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_2_seguimiento', to='cms.url', verbose_name='url del botón 2'),
        ),
        migrations.AlterField(
            model_name='seguimientoindicaciones',
            name='enlace_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_enlace_seguimiento', to='cms.url', verbose_name='url del enlace'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_servicio', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='primera_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primera_url_boton_servicios', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='tercera_seccion_primer_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_primer_boton_servicios', to='cms.url', verbose_name='url del primer botón'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='tercera_seccion_segundo_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_segundo_boton_servicios', to='cms.url', verbose_name='url del segundo botón'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='primera_seccion_boton_principal_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_principal_starkenpro', to='cms.url', verbose_name='url del botón principal'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starkenpro_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.CreateModel(
            name='NavbarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Grupo'), (2, 'Url')], null=True)),
                ('grupo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo')),
                ('navbar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.navbar', verbose_name='Barra de Navegación')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_navbardetail', to='cms.url', verbose_name='url')),
                ('urls', models.ManyToManyField(blank=True, to='cms.URL', verbose_name='urls')),
            ],
            options={
                'verbose_name': 'Detalle - Barra de Navegación',
                'verbose_name_plural': 'Detalle - Barra de Navegación',
            },
        ),
    ]
