# Generated by Django 3.2.16 on 2022-11-24 03:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('formulario_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título formulario')),
                ('formulario_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción formulario')),
                ('formulario_boton_principal', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón formulario')),
                ('etiqueta_usuario', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta nombre')),
                ('etiqueta_contraseña', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta contraseña')),
                ('primera_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('primera_seccion_subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo')),
                ('primera_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('primera_seccion_boton_secundario', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario')),
                ('segunda_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('segunda_seccion_destacado', models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado')),
                ('segunda_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='decripción')),
                ('segunda_seccion_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('segunda_seccion_boton_secundario', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario')),
                ('segunda_seccion_titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('segunda_seccion_alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('segunda_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='login', verbose_name='imagen')),
                ('tercera_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('tercera_seccion_destacado', models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado')),
                ('tercera_seccion_subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo')),
                ('primera_seccion_ocultar', models.BooleanField(default=False, verbose_name='Ocultar')),
                ('segunda_seccion_ocultar', models.BooleanField(default=False, verbose_name='Ocultar')),
                ('tercera_seccion_ocultar', models.BooleanField(default=False, verbose_name='Ocultar')),
                ('primera_seccion_boton_secundario_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario')),
                ('primera_seccion_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primera_url_boton_login', to='cms.url', verbose_name='url del botón')),
                ('segunda_seccion_boton_secundario_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_url_boton_secundario_segunda_seccion', to='cms.url', verbose_name='url del botón secundario')),
                ('segunda_seccion_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_boton_login_segunda_seccion', to='cms.url', verbose_name='url del botón')),
            ],
            options={
                'verbose_name': 'Login',
                'verbose_name_plural': 'Login',
            },
        ),
        migrations.CreateModel(
            name='LoginBeneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresas', verbose_name='ícono')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.login', verbose_name='Login')),
            ],
            options={
                'verbose_name': 'Beneficios-Login',
                'verbose_name_plural': 'Beneficios-Login',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('formulario_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título formulario')),
                ('formulario_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción formulario')),
                ('formulario_boton_principal', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón formulario')),
                ('etiqueta_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta nombre')),
                ('etiqueta_telefono', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta número telefónico')),
                ('etiqueta_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta email')),
                ('etiqueta_contraseña', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta contraseña')),
                ('etiqueta_confirmar_contraseña', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta confirmar contraseña')),
                ('primera_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('primera_seccion_subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo')),
                ('primera_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('primera_seccion_boton_secundario', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario')),
                ('segunda_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('segunda_seccion_destacado', models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado')),
                ('segunda_seccion_subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo')),
                ('cuarta_seccion_tarjeta_1_titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('cuarta_seccion_tarjeta_1_alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('cuarta_seccion_tarjeta_1_imagen', models.ImageField(blank=True, null=True, upload_to='registro', verbose_name='imagen')),
                ('cuarta_seccion_tarjeta_1_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('cuarta_seccion_tarjeta_1_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('cuarta_seccion_tarjeta_1_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('cuarta_seccion_tarjeta_2_titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('cuarta_seccion_tarjeta_2_alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('cuarta_seccion_tarjeta_2_imagen', models.ImageField(blank=True, null=True, upload_to='registro', verbose_name='imagen')),
                ('cuarta_seccion_tarjeta_2_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('cuarta_seccion_tarjeta_2_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('cuarta_seccion_tarjeta_2_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('primera_seccion_ocultar', models.BooleanField(default=False, verbose_name='Ocultar')),
                ('segunda_seccion_ocultar', models.BooleanField(default=False, verbose_name='Ocultar')),
                ('cuarta_seccion_ocultar', models.BooleanField(default=False, verbose_name='Ocultar')),
                ('cuarta_seccion_tarjeta_1_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_boton_tarjeta_1_registro', to='cms.url', verbose_name='url del botón tarjeta 1')),
                ('cuarta_seccion_tarjeta_2_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_boton_tarjeta_2_registro', to='cms.url', verbose_name='url del botón tarjeta 2')),
                ('primera_seccion_boton_secundario_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registro_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario')),
                ('primera_seccion_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primera_url_boton_registro', to='cms.url', verbose_name='url del botón')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registro',
            },
        ),
        migrations.CreateModel(
            name='RegistroBeneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresas', verbose_name='ícono')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.registro', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Beneficios-Registro',
                'verbose_name_plural': 'Beneficios-Registro',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('primera_seccion_destacado', models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado')),
                ('primera_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('primera_seccion_boton_secundario', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario')),
                ('primera_seccion_titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('primera_seccion_alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('primera_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='servicios', verbose_name='imagen de fondo')),
                ('primera_seccion_titulo_imagen_movil', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen de fondo móvil')),
                ('primera_seccion_alt_imagen_movil', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen de fondo móvil')),
                ('primera_seccion_imagen_movil', models.ImageField(blank=True, null=True, upload_to='carousel', verbose_name='imagen de fondo móvil')),
                ('tercera_seccion_titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('tercera_seccion_alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('tercera_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='servicios', verbose_name='imagen')),
                ('tercera_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('tercera_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('tercera_seccion_titulo_interno', models.CharField(blank=True, max_length=255, null=True, verbose_name='título interno')),
                ('tercera_seccion_subtitulo_interno', models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo interno')),
                ('tercera_seccion_primer_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='primer botón')),
                ('tercera_seccion_segundo_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo botón')),
                ('primera_seccion_ocultar', models.BooleanField(default=False, verbose_name='Ocultar')),
                ('tercera_seccion_ocultar', models.BooleanField(default=False, verbose_name='Ocultar')),
                ('primera_seccion_boton_secundario_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario')),
                ('primera_seccion_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primera_url_boton_servicios', to='cms.url', verbose_name='url del botón')),
                ('segunda_seccion_servicios', models.ManyToManyField(blank=True, to='cms.Servicio', verbose_name='servicios')),
                ('tercera_seccion_primer_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_primer_boton_servicios', to='cms.url', verbose_name='url del primer botón')),
                ('tercera_seccion_segundo_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_segundo_boton_servicios', to='cms.url', verbose_name='url del segundo botón')),
            ],
            options={
                'verbose_name': 'Servicios',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='ServiciosCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios', verbose_name='imagen')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.servicios', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Imágenes',
                'verbose_name_plural': 'Imágenes',
            },
        ),
        migrations.RemoveField(
            model_name='mypymestestimonios',
            name='mypymes',
        ),
        migrations.AlterModelOptions(
            name='starkenprobeneficio',
            options={'verbose_name': 'Beneficio', 'verbose_name_plural': 'Beneficios'},
        ),
        migrations.AlterModelOptions(
            name='starkenpropaso',
            options={'verbose_name': 'Indicaciones', 'verbose_name_plural': 'Indicaciones'},
        ),
        migrations.RenameField(
            model_name='mypymes',
            old_name='tercera_seccion_descripcion',
            new_name='cuarta_seccion_descripcion',
        ),
        migrations.RenameField(
            model_name='recomendaciones',
            old_name='recomendación_descripcion',
            new_name='recomendacion_descripcion',
        ),
        migrations.RenameField(
            model_name='starkenpro',
            old_name='primera_seccion_destacado',
            new_name='cuarta_seccion_destacado',
        ),
        migrations.RenameField(
            model_name='starkenpro',
            old_name='primera_seccion_titulo',
            new_name='cuarta_seccion_titulo',
        ),
        migrations.RemoveField(
            model_name='mypymes',
            name='tercera_seccion_enlace',
        ),
        migrations.RemoveField(
            model_name='mypymes',
            name='tercera_seccion_enlace_url',
        ),
        migrations.RemoveField(
            model_name='mypymes',
            name='tercera_seccion_titulo',
        ),
        migrations.RemoveField(
            model_name='reclamos',
            name='etiqueta_telefono',
        ),
        migrations.RemoveField(
            model_name='reclamos',
            name='formulario_descripcion',
        ),
        migrations.RemoveField(
            model_name='reclamos',
            name='formulario_titulo',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='cuarta_seccion_boton_principal_url',
        ),
        migrations.RemoveField(
            model_name='starkenpro',
            name='etiqueta_email',
        ),
        migrations.RemoveField(
            model_name='starkenpro',
            name='etiqueta_mensaje',
        ),
        migrations.RemoveField(
            model_name='starkenpro',
            name='etiqueta_nombre',
        ),
        migrations.RemoveField(
            model_name='starkenpro',
            name='formulario_boton_principal',
        ),
        migrations.RemoveField(
            model_name='starkenpro',
            name='formulario_descripcion',
        ),
        migrations.RemoveField(
            model_name='starkenpro',
            name='formulario_titulo',
        ),
        migrations.RemoveField(
            model_name='starkenpro',
            name='primera_seccion_descripcion',
        ),
        migrations.AddField(
            model_name='about',
            name='cuarta_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='about',
            name='cuarta_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_url_boton_secundario_cuarta_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='about',
            name='primera_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='about',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='about',
            name='quinta_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='about',
            name='quinta_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_url_boton_secundario_quinta_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='about',
            name='tercera_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='about',
            name='tercera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_url_boton_secundario_tercera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='etiqueta_orden_de_flete',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='número de orden de flete'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='formulario_subtitulo',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='subtitulo'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='primera_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centro_de_ayuda_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='segunda_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='segunda_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centro_de_ayuda_url_boton_secundario_segunda_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='cuarta_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='cuarta_seccion_tarjeta_1_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='cuarta_seccion_tarjeta_1_boton',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='cuarta_seccion_tarjeta_1_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_boton_tarjeta_1_contactanos', to='cms.url', verbose_name='url del botón tarjeta 1'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='cuarta_seccion_tarjeta_1_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='cuarta_seccion_tarjeta_1_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='contactanos', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='cuarta_seccion_tarjeta_1_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='cuarta_seccion_tarjeta_1_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='cuarta_seccion_tarjeta_2_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='cuarta_seccion_tarjeta_2_boton',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='cuarta_seccion_tarjeta_2_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_boton_tarjeta_2_contactanos', to='cms.url', verbose_name='url del botón tarjeta 2'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='cuarta_seccion_tarjeta_2_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='cuarta_seccion_tarjeta_2_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='contactanos', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='cuarta_seccion_tarjeta_2_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='cuarta_seccion_tarjeta_2_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='covid',
            name='primera_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='covid',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='covid_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='datos',
            name='boton',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AddField(
            model_name='datos',
            name='boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='datos',
            name='boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datos_url_boton_secundario', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='datos',
            name='boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_boton_principal_datos', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AddField(
            model_name='datos',
            name='primer_icon',
            field=faicon.fields.FAIconField(blank=True, max_length=50, null=True, verbose_name='ícono primer botón'),
        ),
        migrations.AddField(
            model_name='datos',
            name='segundo_icon',
            field=faicon.fields.FAIconField(blank=True, max_length=50, null=True, verbose_name='ícono segundo botón'),
        ),
        migrations.AddField(
            model_name='dhl',
            name='cuarta_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='dhl',
            name='cuarta_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dhl_url_boton_secundario_cuarta_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='dhl',
            name='primera_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='dhl',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dhl_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='primera_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresas_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='tercera_seccion_titulo_carrusel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título de la sección carrusel de imágenes'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='cuarta_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='cuarta_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internacionales_url_boton_secundario_cuarta_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='primera_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internacionales_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='enviosnacionales',
            name='cuarta_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='enviosnacionales',
            name='cuarta_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nacionales_url_boton_secundario_cuarta_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='enviosnacionales',
            name='primera_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='enviosnacionales',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nacionales_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='enviosnacionales',
            name='tercera_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='enviosnacionales',
            name='tercera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nacionales_url_boton_secundario_tercera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='home',
            name='quinta_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón AppStore'),
        ),
        migrations.AddField(
            model_name='home',
            name='quinta_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_boton_secundario_quinta_seccion', to='cms.url', verbose_name='enlace appstore'),
        ),
        migrations.AddField(
            model_name='home',
            name='segunda_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='home',
            name='segunda_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_boton_secundario_segunda_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='home',
            name='tercera_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='home',
            name='tercera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_boton_secundario_tercera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='miprimerenvio',
            name='primera_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='miprimerenvio',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mi_primer_envio_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='miprimerenviostep',
            name='boton',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AddField(
            model_name='miprimerenviostep',
            name='boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_boton_mi_primer_envio_step', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='cuarta_seccion_boton',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='cuarta_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuarta_url_boton_mypymes', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='primera_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mypymes_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='quinta_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='quinta_seccion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mypymes', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='quinta_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='quinta_seccion_video',
            field=models.URLField(blank=True, null=True, verbose_name='video'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='tercera_seccion_destacado_derecho',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado lado derecho'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='tercera_seccion_titulo_derecho',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título lado derecho'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='etiqueta_apellido_materno',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta apellido materno'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='etiqueta_apellido_paterno',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta apellido paterno'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='etiqueta_direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta dirección'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='etiqueta_inconveniente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta inconveniente'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='etiqueta_numero_orden_de_flete',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta número orden de flete'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='etiqueta_telefono_celular',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta teléfono celular'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='etiqueta_telefono_fijo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta teléfono fijo'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='etiqueta_tipo_cliente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta tipo de cliente'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='etiqueta_tipo_reclamo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta tipo de reclamo'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='formulario_primer_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='primer título formulario'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='formulario_segundo_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo título formulario'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='mensaje',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='mensaje'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='primera_notificacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='primera notificación'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='primera_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamos_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='segunda_notificacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='segunda notificación'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='valor_atencion_al_cliente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='valor atención al cliente'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='valor_destinatario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='valor destinatario'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='valor_orden_de_flete',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='valor orden de flete'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='valor_remitente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='valor remitente'),
        ),
        migrations.AddField(
            model_name='recomendacionesembalaje',
            name='primera_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='recomendacionesembalaje',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_embalaje_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='cuarta_seccion_boton_principal_enlace',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='enlace PlayStore'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='cuarta_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón AppStore'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='cuarta_seccion_boton_secundario_enlace',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='enlace AppStore'),
        ),
        migrations.AddField(
            model_name='starkenpro',
            name='cuarta_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='starkenpro',
            name='cuarta_seccion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='starkenpro', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='starkenpro',
            name='cuarta_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='starkenpro',
            name='cuarta_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='starkenpro',
            name='cuarta_seccion_video',
            field=models.URLField(blank=True, null=True, verbose_name='video'),
        ),
        migrations.AddField(
            model_name='starkenpro',
            name='primera_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='starkenpro',
            name='primera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starkenpro_url_boton_secundario_primera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='starkenpro',
            name='primera_seccion_primer_destacado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='primer destacado'),
        ),
        migrations.AddField(
            model_name='starkenpro',
            name='primera_seccion_primer_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='primer título'),
        ),
        migrations.AddField(
            model_name='starkenpro',
            name='primera_seccion_primera_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='primera descripción'),
        ),
        migrations.AddField(
            model_name='starkenpro',
            name='primera_seccion_segunda_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='segunda descripción'),
        ),
        migrations.AddField(
            model_name='starkenpro',
            name='primera_seccion_segundo_destacado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo destacado'),
        ),
        migrations.AddField(
            model_name='starkenpro',
            name='primera_seccion_segundo_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo título'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='boton',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, max_length=50, null=True, verbose_name='ícono'),
        ),
        migrations.AlterField(
            model_name='covidcomunicado',
            name='primera_seccion_contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='home',
            name='quinta_seccion_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón PlayStore'),
        ),
        migrations.AlterField(
            model_name='home',
            name='quinta_seccion_boton_principal_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quinta_url_boton_principal', to='cms.url', verbose_name='enlace playstore'),
        ),
        migrations.AlterField(
            model_name='mypymes',
            name='tercera_seccion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mypymes', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='etiqueta_rut',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta rut'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='cuarta_seccion_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón PlayStore'),
        ),
        migrations.DeleteModel(
            name='MypymesIndicaciones',
        ),
        migrations.DeleteModel(
            name='MypymesTestimonios',
        ),
    ]
