# Generated by Django 3.2.15 on 2022-10-06 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('primera_seccion_destacado', models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado')),
                ('etiqueta_origen', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta origen')),
                ('etiqueta_destino', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta destino')),
                ('etiqueta_encomienda', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta encomienda')),
                ('etiqueta_dimensiones', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta dimensiones')),
                ('etiqueta_peso', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta peso')),
                ('etiqueta_servicio', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta servicio')),
                ('etiqueta_tipo_de_entrega', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta tipo de entrega')),
                ('boton_principal', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón principal')),
                ('segunda_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('segunda_seccion_advertencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='advertencia')),
            ],
            options={
                'verbose_name': 'Cotizador',
                'verbose_name_plural': 'Cotizadores',
            },
        ),
        migrations.CreateModel(
            name='Boton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta botón')),
                ('destacado', models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado')),
                ('cotizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.cotizador', verbose_name='Cotizador')),
            ],
            options={
                'verbose_name': 'Botón',
                'verbose_name_plural': 'Botones',
            },
        ),
        migrations.CreateModel(
            name='Advertencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('cotizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.cotizador', verbose_name='Cotizador')),
            ],
            options={
                'verbose_name': 'Advertencia',
                'verbose_name_plural': 'Advertencias',
            },
        ),
    ]
