# Generated by Django 3.2.15 on 2022-10-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodeayuda',
            name='primera_seccion_boton_principal',
            field=models.CharField(default='boton', max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='primera_seccion_boton_principal_url',
            field=models.URLField(default='boton', verbose_name='url del botón'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='primera_seccion_descripcion',
            field=models.TextField(blank=True, default='descripcion', verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='primera_seccion_titulo',
            field=models.CharField(default='titulo', max_length=255, verbose_name='título'),
        ),
    ]
