# Generated by Django 3.2.15 on 2022-10-05 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('formulario_titulo', models.CharField(max_length=255, verbose_name='título de formulario')),
                ('formulario_descripcion', models.TextField(blank=True, verbose_name='descripción de formulario')),
                ('formulario_boton_principal', models.CharField(max_length=255, verbose_name='botón de formulario')),
                ('etiqueta_nombre', models.CharField(max_length=255, verbose_name='etiqueta nombre')),
                ('etiqueta_email', models.CharField(max_length=255, verbose_name='etiqueta email')),
                ('etiqueta_mensaje', models.CharField(max_length=255, verbose_name='etiqueta mensaje')),
                ('primera_seccion_titulo', models.CharField(default='', max_length=255, verbose_name='título')),
                ('primera_seccion_descripcion', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('tercera_seccion_imagen', models.ImageField(upload_to='contactanos', verbose_name='imagen')),
                ('tercera_seccion_formulario_titulo', models.CharField(max_length=255, verbose_name='título de formulario')),
                ('tercera_seccion_formulario_boton_principal', models.CharField(max_length=255, verbose_name='botón de formulario')),
                ('tercera_seccion_etiqueta_nombre', models.CharField(max_length=255, verbose_name='etiqueta nombre')),
                ('tercera_seccion_etiqueta_email', models.CharField(max_length=255, verbose_name='etiqueta email')),
                ('tercera_seccion_etiqueta_comentario', models.CharField(max_length=255, verbose_name='etiqueta comentario')),
            ],
            options={
                'verbose_name': 'Contáctanos',
                'verbose_name_plural': 'Contáctanos',
            },
        ),
        migrations.AlterModelOptions(
            name='redessociales',
            options={'verbose_name': 'Artículos Redes Sociales', 'verbose_name_plural': 'Artículos Redes Sociales'},
        ),
        migrations.CreateModel(
            name='Iconos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.ImageField(upload_to='iconos', verbose_name='imagen')),
                ('contactanos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.contactanos', verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Íconos',
                'verbose_name_plural': 'Íconos',
            },
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='datos', verbose_name='imagen')),
                ('titulo', models.CharField(default='', max_length=255, verbose_name='título')),
                ('primera_descripcion', models.TextField(blank=True, default='', verbose_name='primera descripción')),
                ('segunda_descripcion', models.TextField(blank=True, default='', verbose_name='segunda descripción')),
                ('contactanos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.contactanos', verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Contáctanos Datos',
                'verbose_name_plural': 'Contáctanos Datos',
            },
        ),
    ]
