# Generated by Django 4.1.1 on 2022-09-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='fifth_section_button',
            new_name='fifth_section_main_button',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='fifth_section_button_url',
            new_name='fifth_section_main_button_url',
        ),
    ]
