# Generated by Django 4.1.1 on 2022-09-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_rename_fifth_section_button_home_fifth_section_main_button_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='fifth_section_words',
            field=models.CharField(max_length=255, verbose_name='palabras'),
        ),
    ]
