# Generated by Django 3.2.16 on 2022-11-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20221103_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='boton',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_boton_cotizador', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='segunda_seccion_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón principal'),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='segunda_seccion_boton_principal_destacado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado botón principal'),
        ),
    ]
