# Generated by Django 3.2.16 on 2022-11-24 05:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20221123_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='quinta_seccion_boton_principal_url',
            new_name='quinta_seccion_app_store_url',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='quinta_seccion_boton_secundario_url',
            new_name='quinta_seccion_google_play_url',
        ),
        migrations.RemoveField(
            model_name='home',
            name='quinta_seccion_boton_principal',
        ),
        migrations.RemoveField(
            model_name='home',
            name='quinta_seccion_boton_secundario',
        ),
        migrations.RemoveField(
            model_name='starkenpro',
            name='primera_seccion_mensaje',
        ),
        migrations.RemoveField(
            model_name='starkenpro',
            name='primera_seccion_primer_destacado',
        ),
        migrations.RemoveField(
            model_name='starkenpro',
            name='primera_seccion_segundo_destacado',
        ),
        migrations.AddField(
            model_name='starkenpro',
            name='cuarta_seccion_descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='starkenpro',
            name='cuarta_seccion_subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo'),
        ),
        migrations.AlterField(
            model_name='home',
            name='primera_seccion_descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='home',
            name='segunda_seccion_descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='home',
            name='tercera_seccion_descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='primera_seccion_primera_descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Primera descripción'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='primera_seccion_segunda_descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Segunda descripción'),
        ),
    ]
