# Generated by Django 3.2.15 on 2022-10-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20221004_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centrodeayuda',
            old_name='cuarta_seccion_image',
            new_name='cuarta_seccion_imagen',
        ),
        migrations.RenameField(
            model_name='centrodeayuda',
            old_name='etiqueta_message',
            new_name='etiqueta_mensaje',
        ),
        migrations.RenameField(
            model_name='centrodeayuda',
            old_name='etiqueta_name',
            new_name='etiqueta_nombre',
        ),
    ]
