# Generated by Django 3.2.15 on 2022-10-05 17:20

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20221005_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cuarta_seccion_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AlterField(
            model_name='about',
            name='cuarta_seccion_boton_principal_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='about',
            name='cuarta_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='about',
            name='cuarta_seccion_destacado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado'),
        ),
        migrations.AlterField(
            model_name='about',
            name='cuarta_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='about',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='about',
            name='primera_seccion_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AlterField(
            model_name='about',
            name='primera_seccion_boton_principal_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='about',
            name='primera_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='about',
            name='primera_seccion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='about',
            name='primera_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='about',
            name='quinta_seccion_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AlterField(
            model_name='about',
            name='quinta_seccion_boton_principal_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='about',
            name='quinta_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='about',
            name='quinta_seccion_destacado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado'),
        ),
        migrations.AlterField(
            model_name='about',
            name='quinta_seccion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='about',
            name='quinta_seccion_subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo'),
        ),
        migrations.AlterField(
            model_name='about',
            name='quinta_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='about',
            name='segunda_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='about',
            name='segunda_seccion_destacado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado'),
        ),
        migrations.AlterField(
            model_name='about',
            name='segunda_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='about',
            name='tercera_seccion_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AlterField(
            model_name='about',
            name='tercera_seccion_boton_principal_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='about',
            name='tercera_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='about',
            name='tercera_seccion_destacado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado'),
        ),
        migrations.AlterField(
            model_name='about',
            name='tercera_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='about',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fecha_de_actualizacion',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='primera_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='primera_seccion_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='primera_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='redes_sociales',
            field=models.ManyToManyField(blank=True, to='cms.RedesSociales', verbose_name='Redes Sociales'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='segunda_seccion_contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='segunda_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='segunda_seccion_etiqueta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='segunda_seccion_fecha_de_creacion',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='segunda_seccion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='segunda_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tercera_seccion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tercera_seccion_primer_boton',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='primer botón'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tercera_seccion_segundo_boton',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo botón'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tercera_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tercera_seccion_url_primer_boton',
            field=models.URLField(blank=True, null=True, verbose_name='url del primer botón'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tercera_seccion_url_segundo_boton',
            field=models.URLField(blank=True, null=True, verbose_name='url del segundo botón'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('noticia', 'Noticia'), ('responsabilidad social', 'Responsabilidad social'), ('sustentabilidad', 'Sustentabilidad')], max_length=255, null=True, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='boton',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='boton_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='descripción corta'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel', to='cms.home'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='carousel', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='titulo_corto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título corto'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='cuarta_seccion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='CentrodeAyuda', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='etiqueta_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='etiqueta_email_contacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta email'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='etiqueta_mensaje',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='mensaje'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='etiqueta_mensaje_contacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta mensaje'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='etiqueta_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='etiqueta_nombre_contacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta nombre'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='etiqueta_telefono_contacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta phone'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='etiqueta_tipo_de_negocio_contacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta tipo de negocio'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='formulario_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='formulario_boton_principal_contacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón formulario'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='formulario_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='formulario_descripcion_contacto',
            field=models.TextField(blank=True, null=True, verbose_name='descripción formulario'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='formulario_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='formulario_titulo_contacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título formulario'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='primera_seccion_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='primera_seccion_boton_principal_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='primera_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='primera_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='segunda_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='segunda_seccion_destacado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='segunda_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='tercera_seccion_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='tercera_seccion_boton_principal_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='tercera_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='tercera_seccion_destacado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='tercera_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='centrodeayudabeneficio',
            name='centro_de_ayuda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.centrodeayuda', verbose_name='Centro de Ayuda'),
        ),
        migrations.AlterField(
            model_name='centrodeayudabeneficio',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='centrodeayudabeneficio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='centro_de_ayuda', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='centrodeayudabeneficio',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='centrodeayudapregunta',
            name='centro_de_ayuda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.centrodeayuda', verbose_name='Centro de Ayuda'),
        ),
        migrations.AlterField(
            model_name='centrodeayudapregunta',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='centrodeayudapregunta',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='etiqueta_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta email'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='etiqueta_mensaje',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta mensaje'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='etiqueta_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta nombre'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='formulario_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón de formulario'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='formulario_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción de formulario'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='formulario_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título de formulario'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='primera_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='primera_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='tercera_seccion_etiqueta_comentario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta comentario'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='tercera_seccion_etiqueta_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta email'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='tercera_seccion_etiqueta_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta nombre'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='tercera_seccion_formulario_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón de formulario'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='tercera_seccion_formulario_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título de formulario'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='tercera_seccion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='contactanos', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='contactanos',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='contenidoarticulo',
            name='articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.articulo', verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='contenidoarticulo',
            name='contenido',
            field=models.TextField(blank=True, null=True, verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='contenidoarticulo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='contenidoarticulo',
            name='fecha_de_creacion',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='contenidoarticulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='contenidoarticulo',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='contactanos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.contactanos', verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='datos', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='primera_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='primera descripción'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='segunda_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='segunda descripción'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cuarta_seccion_tarjeta_1_boton',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cuarta_seccion_tarjeta_1_boton_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cuarta_seccion_tarjeta_1_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cuarta_seccion_tarjeta_1_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='home', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cuarta_seccion_tarjeta_1_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cuarta_seccion_tarjeta_2_boton',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cuarta_seccion_tarjeta_2_boton_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cuarta_seccion_tarjeta_2_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cuarta_seccion_tarjeta_2_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='home', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cuarta_seccion_tarjeta_2_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='home',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='home',
            name='primera_seccion_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón principal'),
        ),
        migrations.AlterField(
            model_name='home',
            name='primera_seccion_boton_principal_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del botón principal'),
        ),
        migrations.AlterField(
            model_name='home',
            name='primera_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AlterField(
            model_name='home',
            name='primera_seccion_boton_secundario_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del botón secundario'),
        ),
        migrations.AlterField(
            model_name='home',
            name='primera_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='home',
            name='primera_seccion_destacado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado'),
        ),
        migrations.AlterField(
            model_name='home',
            name='primera_seccion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='home', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='home',
            name='primera_seccion_link',
            field=models.URLField(blank=True, null=True, verbose_name='enlace'),
        ),
        migrations.AlterField(
            model_name='home',
            name='primera_seccion_link_texto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='texto del enlace'),
        ),
        migrations.AlterField(
            model_name='home',
            name='primera_seccion_subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo'),
        ),
        migrations.AlterField(
            model_name='home',
            name='primera_seccion_subtitulo_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='home',
            name='primera_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='home',
            name='quinta_seccion_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AlterField(
            model_name='home',
            name='quinta_seccion_boton_principal_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='home',
            name='quinta_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='home',
            name='quinta_seccion_palabras',
            field=models.CharField(blank=True, help_text='separadas por coma', max_length=255, null=True, verbose_name='palabras'),
        ),
        migrations.AlterField(
            model_name='home',
            name='quinta_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='home',
            name='segunda_seccion_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón principal'),
        ),
        migrations.AlterField(
            model_name='home',
            name='segunda_seccion_boton_principal_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del botón principal'),
        ),
        migrations.AlterField(
            model_name='home',
            name='segunda_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='home',
            name='segunda_seccion_destacado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado'),
        ),
        migrations.AlterField(
            model_name='home',
            name='segunda_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='home',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='cms.Servicio', verbose_name='servicios'),
        ),
        migrations.AlterField(
            model_name='home',
            name='tercera_seccion_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón principal'),
        ),
        migrations.AlterField(
            model_name='home',
            name='tercera_seccion_boton_principal_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del botón principal'),
        ),
        migrations.AlterField(
            model_name='home',
            name='tercera_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='home',
            name='tercera_seccion_destacado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado'),
        ),
        migrations.AlterField(
            model_name='home',
            name='tercera_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='home',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='iconos',
            name='contactanos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.contactanos', verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='iconos',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='iconos', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='boton',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='boton_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='cms.home'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='opciones', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.preguntascategoria', verbose_name='Preguntas'),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='pregunta_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='pregunta descripción'),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='pregunta_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='pregunta título'),
        ),
        migrations.AlterField(
            model_name='preguntascategoria',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.preguntasfrecuentes', verbose_name='Categoría de Preguntas'),
        ),
        migrations.AlterField(
            model_name='preguntascategoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='preguntascategoria',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='preguntascategoria',
            name='titulo_categoria',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='preguntasfrecuentes',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='preguntasfrecuentes',
            name='primera_seccion_boton_buscar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AlterField(
            model_name='preguntasfrecuentes',
            name='primera_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='preguntasfrecuentes',
            name='segunda_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='preguntasfrecuentes',
            name='segunda_seccion_descripcion_primer_bloque',
            field=models.TextField(blank=True, null=True, verbose_name='descripción primer bloque'),
        ),
        migrations.AlterField(
            model_name='preguntasfrecuentes',
            name='segunda_seccion_descripcion_segundo_bloque',
            field=models.TextField(blank=True, null=True, verbose_name='descripción segundo bloque'),
        ),
        migrations.AlterField(
            model_name='preguntasfrecuentes',
            name='segunda_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='preguntasfrecuentes',
            name='segunda_seccion_titulo_primer_bloque',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título primer bloque'),
        ),
        migrations.AlterField(
            model_name='preguntasfrecuentes',
            name='segunda_seccion_titulo_segundo_bloque',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título segundo bloque'),
        ),
        migrations.AlterField(
            model_name='preguntasfrecuentes',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='redessociales',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='redessociales',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='boton',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='boton_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='etiqueta_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta email'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='etiqueta_mensaje',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta mensaje'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='etiqueta_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta nombre'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='formulario_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón de formulario'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='formulario_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción de formulario'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='formulario_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título de formulario'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='primera_seccion_boton_principal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='primera_seccion_boton_principal_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='primera_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='primera_seccion_destacado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='primera_seccion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='starkenpro', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='primera_seccion_mensaje',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='mensaje'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='primera_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='segunda_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='segunda_seccion_destacado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='segunda_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='tercera_seccion_destacado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='tercera_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='starkenpro',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='starkenprobeneficio',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='starkenprobeneficio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='starkenpro', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='starkenprobeneficio',
            name='starken_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.starkenpro', verbose_name='starken PRO'),
        ),
        migrations.AlterField(
            model_name='starkenprobeneficio',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='starkenpropaso',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='starkenpropaso',
            name='starken_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.starkenpro', verbose_name='starken PRO'),
        ),
        migrations.AlterField(
            model_name='starkenpropaso',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='terminosdeservicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='terminosdeservicio',
            name='primera_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='terminosdeservicio',
            name='primera_seccion_subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo'),
        ),
        migrations.AlterField(
            model_name='terminosdeservicio',
            name='primera_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='terminosdeservicio',
            name='segunda_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='terminosdeservicio',
            name='segunda_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='terminosdeservicio',
            name='tercera_seccion_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='terminosdeservicio',
            name='tercera_seccion_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='terminosdeservicio',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='terminosdeserviciopunto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción de término'),
        ),
        migrations.AlterField(
            model_name='terminosdeserviciopunto',
            name='terminos_de_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.terminosdeservicio', verbose_name='Términos de Servicio'),
        ),
        migrations.AlterField(
            model_name='terminosdeserviciopunto',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título de término'),
        ),
    ]
