# Generated by Django 3.2.15 on 2022-10-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20221005_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='primera_seccion_descripcion',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='primera_seccion_logo',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='primera_seccion_titulo',
        ),
    ]
