# Generated by Django 3.2.16 on 2022-11-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20221124_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='etiqueta_confirmar_contraseña',
        ),
        migrations.AddField(
            model_name='registro',
            name='etiqueta_apellido',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta apellido'),
        ),
        migrations.AddField(
            model_name='registro',
            name='etiqueta_comuna',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta comuna'),
        ),
        migrations.AddField(
            model_name='registro',
            name='etiqueta_direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta dirección'),
        ),
        migrations.AddField(
            model_name='registro',
            name='etiqueta_movil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta número móvil'),
        ),
        migrations.AddField(
            model_name='registro',
            name='etiqueta_rut',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta rut'),
        ),
        migrations.AddField(
            model_name='registro',
            name='etiqueta_sucursal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta sucursal'),
        ),
    ]
