# Generated by Django 3.2.15 on 2022-10-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20221004_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminosdeservicio',
            name='segunda_seccion_descripcion',
            field=models.TextField(blank=True, default='', verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='terminosdeservicio',
            name='segunda_seccion_titulo',
            field=models.CharField(default='', max_length=255, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='terminosdeservicio',
            name='tercera_seccion_descripcion',
            field=models.TextField(blank=True, default='', verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='terminosdeservicio',
            name='tercera_seccion_titulo',
            field=models.CharField(default='', max_length=255, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='terminosdeserviciopunto',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='descripción de término'),
        ),
        migrations.AddField(
            model_name='terminosdeserviciopunto',
            name='titulo',
            field=models.CharField(default='', max_length=255, verbose_name='título de término'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='etiqueta_email_contacto',
            field=models.CharField(max_length=255, verbose_name='etiqueta email'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='etiqueta_mensaje_contacto',
            field=models.CharField(max_length=255, verbose_name='etiqueta mensaje'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='etiqueta_nombre_contacto',
            field=models.CharField(max_length=255, verbose_name='etiqueta nombre'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='etiqueta_telefono_contacto',
            field=models.CharField(max_length=255, verbose_name='etiqueta phone'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='etiqueta_tipo_de_negocio_contacto',
            field=models.CharField(max_length=255, verbose_name='etiqueta tipo de negocio'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='formulario_boton_principal_contacto',
            field=models.CharField(max_length=255, verbose_name='botón formulario'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='formulario_descripcion_contacto',
            field=models.TextField(blank=True, verbose_name='descripción formulario'),
        ),
        migrations.AlterField(
            model_name='centrodeayuda',
            name='formulario_titulo_contacto',
            field=models.CharField(max_length=255, verbose_name='título formulario'),
        ),
        migrations.AlterField(
            model_name='terminosdeservicio',
            name='primera_seccion_descripcion',
            field=models.TextField(blank=True, default='', verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='terminosdeservicio',
            name='primera_seccion_subtitulo',
            field=models.CharField(default='', max_length=255, verbose_name='subtítulo'),
        ),
        migrations.AlterField(
            model_name='terminosdeservicio',
            name='primera_seccion_titulo',
            field=models.CharField(default='', max_length=255, verbose_name='título'),
        ),
    ]
