# Generated by Django 3.2.15 on 2022-10-07 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_accion_dhl_modalidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('primera_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('primera_seccion_boton_url', models.URLField(blank=True, null=True, verbose_name='url del botón')),
                ('primera_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='empresas', verbose_name='imagen de fondo')),
                ('segunda_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('segunda_seccion_destacado', models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado')),
                ('segunda_seccion_subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo')),
                ('tercera_seccion_imagen_fondo', models.ImageField(blank=True, null=True, upload_to='empresas', verbose_name='imagen de fondo')),
                ('formulario_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título formulario')),
                ('formulario_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción formulario')),
                ('formulario_boton_principal', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón formulario')),
                ('etiqueta_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta nombre')),
                ('etiqueta_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta email')),
                ('etiqueta_telefono', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta número telefónico')),
                ('etiqueta_tipo_de_negocio', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta tipo de negocio')),
                ('tercera_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='empresas', verbose_name='logo')),
                ('tercera_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('tercera_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('tercera_seccion_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('tercera_seccion_boton_url', models.URLField(blank=True, null=True, verbose_name='url del botón')),
                ('cuarta_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='empresas', verbose_name='imagen')),
                ('cuarta_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('cuarta_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('cuarta_seccion_titulo_interno', models.CharField(blank=True, max_length=255, null=True, verbose_name='título interno')),
                ('cuarta_seccion_subtitulo_interno', models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo interno')),
                ('cuarta_seccion_primer_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='primer botón')),
                ('cuarta_seccion_primer_boton_url', models.URLField(blank=True, null=True, verbose_name='url del primer botón')),
                ('cuarta_seccion_segundo_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo botón')),
                ('cuarta_seccion_segundo_boton_url', models.URLField(blank=True, null=True, verbose_name='url del segundo botón')),
                ('quinta_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('quinta_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('quinta_seccion_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('quinta_seccion_boton_url', models.URLField(blank=True, null=True, verbose_name='url del botón')),
                ('quinta_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='empresas', verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='EmpresasCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresas', verbose_name='imagen')),
                ('beneficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.empresas', verbose_name='Beneficio')),
            ],
            options={
                'verbose_name': 'Imágenes',
                'verbose_name_plural': 'Imágenes',
            },
        ),
        migrations.CreateModel(
            name='EmpresasBeneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresas', verbose_name='ícono')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('beneficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.empresas', verbose_name='Beneficio')),
            ],
            options={
                'verbose_name': 'Beneficios',
                'verbose_name_plural': 'Beneficios',
            },
        ),
    ]
