# Generated by Django 4.1.1 on 2022-09-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_service_alter_home_fifth_section_words_option_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('first_section_image', models.ImageField(upload_to='about', verbose_name='imagen')),
                ('first_section_title', models.CharField(max_length=255, verbose_name='título')),
                ('first_section_description', models.TextField(blank=True, verbose_name='descripción')),
                ('first_section_main_button', models.CharField(max_length=255, verbose_name='botón')),
                ('first_section_main_button_url', models.URLField(verbose_name='url del botón')),
                ('second_section_title', models.CharField(max_length=255, verbose_name='título')),
                ('second_section_title_highlight', models.CharField(max_length=255, verbose_name='destacado')),
                ('second_section_description', models.TextField(blank=True, verbose_name='descripción')),
                ('third_section_title', models.CharField(max_length=255, verbose_name='título')),
                ('third_section_highlight', models.CharField(max_length=255, verbose_name='destacado')),
                ('third_section_description', models.TextField(blank=True, verbose_name='descripción')),
                ('third_section_main_button', models.CharField(max_length=255, verbose_name='botón')),
                ('third_section_main_button_url', models.URLField(verbose_name='url del botón')),
                ('fourth_section_title', models.CharField(max_length=255, verbose_name='título')),
                ('fourth_section_highlight', models.CharField(max_length=255, verbose_name='destacado')),
                ('fourth_section_description', models.TextField(blank=True, verbose_name='descripción')),
                ('fourth_section_main_button', models.CharField(max_length=255, verbose_name='botón')),
                ('fourth_section_main_button_url', models.URLField(verbose_name='url del botón')),
                ('fifth_section_image', models.ImageField(upload_to='about', verbose_name='imagen')),
                ('fifth_section_title', models.CharField(max_length=255, verbose_name='título')),
                ('fifth_section_title_highlight', models.CharField(max_length=255, verbose_name='destacado')),
                ('fifth_section_subtitle', models.CharField(max_length=255, verbose_name='subtítulo')),
                ('fifth_section_description', models.TextField(blank=True, verbose_name='descripción')),
                ('fifth_section_main_button', models.CharField(max_length=255, verbose_name='botón')),
                ('fifth_section_main_button_url', models.URLField(verbose_name='url del botón')),
            ],
            options={
                'verbose_name': 'somos STARKEN',
                'verbose_name_plural': 'somos STARKEN',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles', verbose_name='imagen')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('type', models.CharField(choices=[('noticia', 'Noticia'), ('responsabilidad social', 'Responsabilidad social'), ('sustentabilidad', 'Sustentabilidad')], max_length=255, verbose_name='tipo')),
                ('created_at', models.DateField(verbose_name='fecha de creación')),
                ('updated_at', models.DateField(verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'artículo',
                'verbose_name_plural': 'artículos',
            },
        ),
    ]
