# Generated by Django 3.2.15 on 2022-10-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20221005_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='segunda_seccion_contenido',
            new_name='primera_seccion_contenido',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='segunda_seccion_descripcion',
            new_name='primera_seccion_descripcion',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='segunda_seccion_etiqueta',
            new_name='primera_seccion_etiqueta',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='segunda_seccion_fecha_de_creacion',
            new_name='primera_seccion_fecha_de_creacion',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='tercera_seccion_imagen',
            new_name='primera_seccion_imagen',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='tercera_seccion_titulo',
            new_name='primera_seccion_titulo',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='tercera_seccion_primer_boton',
            new_name='segunda_seccion_primer_boton',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='tercera_seccion_segundo_boton',
            new_name='segunda_seccion_segundo_boton',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='tercera_seccion_url_primer_boton',
            new_name='segunda_seccion_url_primer_boton',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='tercera_seccion_url_segundo_boton',
            new_name='segunda_seccion_url_segundo_boton',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='redes_sociales',
        ),
        migrations.DeleteModel(
            name='ContenidoArticulo',
        ),
        migrations.DeleteModel(
            name='RedesSociales',
        ),
    ]
