# Generated by Django 3.2.16 on 2022-11-24 06:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20221124_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamos',
            name='tercera_seccion_enlace_url',
        ),
        migrations.RemoveField(
            model_name='reclamos',
            name='tercera_seccion_subtitulo',
        ),
        migrations.AddField(
            model_name='reclamos',
            name='tercera_seccion_boton',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='tercera_seccion_boton_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='botón secundario'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='tercera_seccion_boton_secundario_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamos_url_boton_secundario_tercera_seccion', to='cms.url', verbose_name='url del botón secundario'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='tercera_seccion_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamos_url_boton_tercera_seccion', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='tercera_seccion_descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='descripción'),
        ),
    ]
