# Generated by Django 3.2.15 on 2022-10-05 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20221004_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntasFrecuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('primera_seccion_titulo', models.CharField(default='', max_length=255, verbose_name='título')),
                ('primera_seccion_boton_buscar', models.CharField(default='', max_length=255, null=True, verbose_name='botón')),
                ('segunda_seccion_titulo', models.CharField(default='', max_length=255, verbose_name='título')),
                ('segunda_seccion_descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('segunda_seccion_titulo_primer_bloque', models.CharField(default='', max_length=255, verbose_name='título primer bloque')),
                ('segunda_seccion_descripcion_primer_bloque', models.TextField(blank=True, verbose_name='descripción primer bloque')),
                ('segunda_seccion_titulo_segundo_bloque', models.CharField(default='', max_length=255, verbose_name='título segundo bloque')),
                ('segunda_seccion_descripcion_segundo_bloque', models.TextField(blank=True, verbose_name='descripción segundo bloque')),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
            },
        ),
        migrations.CreateModel(
            name='PreguntasCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('titulo_categoria', models.CharField(default='', max_length=255, verbose_name='título')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.preguntasfrecuentes', verbose_name='Categoría de Preguntas')),
            ],
            options={
                'verbose_name': 'titulo de categoría',
                'verbose_name_plural': 'títulos de categoría',
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_titulo', models.CharField(default='', max_length=255, verbose_name='pregunta título')),
                ('pregunta_descripcion', models.TextField(blank=True, default='', verbose_name='pregunta descripción')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.preguntascategoria', verbose_name='Preguntas')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
            },
        ),
    ]
