# Generated by Django 3.2.15 on 2022-10-07 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_empresas_empresasbeneficios_empresascarrusel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnviosInternacionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo')),
                ('primera_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('primera_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('primera_seccion_boton_url', models.URLField(blank=True, null=True, verbose_name='url del botón')),
                ('primera_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='envios internacionales', verbose_name='imagen de fondo')),
                ('segunda_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('segunda_seccion_destacado', models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado')),
                ('segunda_seccion_subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo')),
                ('tercera_seccion_imagen_primer_bloque', models.ImageField(blank=True, null=True, upload_to='envios internacionales', verbose_name='imagen de fondo primer bloque')),
                ('tercera_seccion_titulo_primer_bloque', models.CharField(blank=True, max_length=255, null=True, verbose_name='título primer bloque')),
                ('tercera_seccion_descripcion_primer_bloque', models.TextField(blank=True, null=True, verbose_name='descripción primer bloque')),
                ('tercera_seccion_boton_primer_bloque', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón primer bloque')),
                ('tercera_seccion_boton_url_primer_bloque', models.URLField(blank=True, null=True, verbose_name='url del botón primer bloque')),
                ('tercera_seccion_imagen_segundo_bloque', models.ImageField(blank=True, null=True, upload_to='envios internacionales', verbose_name='imagen de fondo segundo bloque')),
                ('tercera_seccion_titulo_segundo_bloque', models.CharField(blank=True, max_length=255, null=True, verbose_name='título segundo bloque')),
                ('tercera_seccion_descripcion_segundo_bloque', models.TextField(blank=True, null=True, verbose_name='descripción segundo bloque')),
                ('tercera_seccion_boton_segundo_bloque', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón segundo bloque')),
                ('tercera_seccion_boton_url_segundo_bloque', models.URLField(blank=True, null=True, verbose_name='url del botón segundo bloque')),
                ('cuarta_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='envios internacionales', verbose_name='imagen')),
                ('cuarta_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('cuarta_seccion_destacado', models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado')),
                ('cuarta_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('cuarta_seccion_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('cuarta_seccion_boton_url', models.URLField(blank=True, null=True, verbose_name='url del botón')),
                ('quinta_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('quinta_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('quinta_seccion_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('quinta_seccion_boton_url', models.URLField(blank=True, null=True, verbose_name='url del botón')),
                ('quinta_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='envios internacionales', verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'Envíos Internacionales',
                'verbose_name_plural': 'Envíos Internacionales',
            },
        ),
        migrations.RemoveField(
            model_name='dhl',
            name='primera_seccion_destacado',
        ),
        migrations.AddField(
            model_name='dhl',
            name='primera_seccion_subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo'),
        ),
        migrations.CreateModel(
            name='EnviosInternacionalesBeneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='envios internacionales', verbose_name='ícono')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('beneficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.enviosinternacionales', verbose_name='Beneficio')),
            ],
            options={
                'verbose_name': 'Beneficios',
                'verbose_name_plural': 'Beneficios',
            },
        ),
    ]
