# Generated by Django 3.2.15 on 2022-10-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20221005_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntascategoria',
            options={'verbose_name': 'FAQ - Categoría', 'verbose_name_plural': 'FAQ - Categoría'},
        ),
        migrations.AlterModelOptions(
            name='preguntasfrecuentes',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.RenameField(
            model_name='preguntasfrecuentes',
            old_name='segunda_seccion_descripcion',
            new_name='tercera_seccion_descripcion',
        ),
        migrations.RenameField(
            model_name='preguntasfrecuentes',
            old_name='segunda_seccion_descripcion_primer_bloque',
            new_name='tercera_seccion_descripcion_primer_bloque',
        ),
        migrations.RenameField(
            model_name='preguntasfrecuentes',
            old_name='segunda_seccion_descripcion_segundo_bloque',
            new_name='tercera_seccion_descripcion_segundo_bloque',
        ),
        migrations.RenameField(
            model_name='preguntasfrecuentes',
            old_name='segunda_seccion_titulo',
            new_name='tercera_seccion_titulo',
        ),
        migrations.RenameField(
            model_name='preguntasfrecuentes',
            old_name='segunda_seccion_titulo_primer_bloque',
            new_name='tercera_seccion_titulo_primer_bloque',
        ),
        migrations.RenameField(
            model_name='preguntasfrecuentes',
            old_name='segunda_seccion_titulo_segundo_bloque',
            new_name='tercera_seccion_titulo_segundo_bloque',
        ),
        migrations.RemoveField(
            model_name='preguntascategoria',
            name='categoria',
        ),
        migrations.AddField(
            model_name='preguntasfrecuentes',
            name='segunda_seccion_categoria',
            field=models.ManyToManyField(blank=True, to='cms.PreguntasCategoria', verbose_name='Categorías'),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='cms.preguntascategoria', verbose_name='Preguntas'),
        ),
    ]
