# Generated by Django 3.2.15 on 2022-10-07 18:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20221007_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhl',
            name='tercera_seccion_descripcion',
        ),
        migrations.RemoveField(
            model_name='dhl',
            name='tercera_seccion_subtitulo',
        ),
        migrations.RemoveField(
            model_name='dhl',
            name='tercera_seccion_titulo',
        ),
        migrations.AddField(
            model_name='dhl',
            name='tercera_seccion_contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='contenido'),
        ),
    ]
