# Generated by Django 4.1.1 on 2022-09-30 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_about_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='fifth_section_title_highlight',
            new_name='fifth_section_highlight',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='second_section_title_highlight',
            new_name='second_section_highlight',
        ),
    ]
