# Generated by Django 4.1.1 on 2022-09-30 23:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_rename_fifth_section_title_highlight_about_fifth_section_highlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='contenido'),
            preserve_default=False,
        ),
    ]
