# Generated by Django 3.2.15 on 2022-10-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20221005_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodeayuda',
            name='tercera_seccion_preguntas',
            field=models.ManyToManyField(blank=True, to='cms.PreguntasCategoria', verbose_name='Preguntas'),
        ),
    ]
