# Generated by Django 3.2.15 on 2022-10-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_centrodeayuda_tercera_seccion_preguntas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CentrodeAyudaPregunta',
        ),
    ]
