# Generated by Django 3.2.15 on 2022-10-07 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_enviosnacionales_enviosnacionalesbeneficios_enviosnacionalesrecomendaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiPrimerEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('primera_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('primera_seccion_boton_url', models.URLField(blank=True, null=True, verbose_name='url del botón')),
                ('primera_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='envios nacionales', verbose_name='imagen de fondo')),
            ],
            options={
                'verbose_name': 'Mi Primer Envío',
                'verbose_name_plural': 'Mi Primer Envío',
            },
        ),
        migrations.CreateModel(
            name='MiPrimerEnvioStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='envios nacionales', verbose_name='ícono')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('beneficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.miprimerenvio', verbose_name='Step')),
            ],
            options={
                'verbose_name': 'Indicaciones',
                'verbose_name_plural': 'Indicaciones',
            },
        ),
    ]
