# Generated by Django 4.1.1 on 2022-09-30 23:28

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarkenPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('first_section_image', models.ImageField(upload_to='starkenpro', verbose_name='imagen')),
                ('first_section_title', models.CharField(max_length=255, verbose_name='título')),
                ('first_section_highlight', models.CharField(max_length=255, verbose_name='destacado')),
                ('first_section_description', models.TextField(blank=True, verbose_name='descripción')),
                ('first_section_main_button', models.CharField(max_length=255, verbose_name='botón')),
                ('first_section_main_button_url', models.URLField(verbose_name='url del botón')),
                ('fisrt_section_message', models.CharField(max_length=255, verbose_name='mensaje')),
                ('form_title', models.CharField(max_length=255, verbose_name='título')),
                ('form_description', models.TextField(blank=True, verbose_name='descripción')),
                ('form_main_button', models.CharField(max_length=255, verbose_name='botón')),
                ('label_name', models.CharField(max_length=255, verbose_name='nombre')),
                ('label_email', models.CharField(max_length=255, verbose_name='email')),
                ('label_message', models.CharField(max_length=255, verbose_name='mensaje')),
                ('second_section_title', models.CharField(max_length=255, verbose_name='título')),
                ('second_section_highlight', models.CharField(max_length=255, verbose_name='destacado')),
                ('second_section_description', models.TextField(blank=True, verbose_name='descripción')),
                ('third_section_title', models.CharField(max_length=255, verbose_name='título')),
                ('third_section_highlight', models.CharField(max_length=255, verbose_name='destacado')),
            ],
            options={
                'verbose_name': 'starken PRO',
                'verbose_name_plural': 'starken PRO',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='contenido'),
        ),
        migrations.CreateModel(
            name='StarkenProStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('starken_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.starkenpro', verbose_name='starken PRO')),
            ],
            options={
                'verbose_name': 'paso',
                'verbose_name_plural': 'pasos',
            },
        ),
        migrations.CreateModel(
            name='StarkenProBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('image', models.ImageField(upload_to='starkenpro', verbose_name='imagen')),
                ('starken_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.starkenpro', verbose_name='starken PRO')),
            ],
            options={
                'verbose_name': 'beneficio',
                'verbose_name_plural': 'beneficios',
            },
        ),
    ]
