# Generated by Django 4.1.1 on 2022-09-30 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_starkenpro_alter_article_content_starkenprostep_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starkenpro',
            old_name='fisrt_section_message',
            new_name='first_section_message',
        ),
    ]
