# Generated by Django 3.2.15 on 2022-10-07 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_miprimerenvio_miprimerenviostep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mypymes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('primera_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('primera_seccion_boton_url', models.URLField(blank=True, null=True, verbose_name='url del botón')),
                ('primera_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='mypymes', verbose_name='imagen de fondo')),
                ('primera_seccion_video', models.FileField(blank=True, null=True, upload_to='mypymes', verbose_name='video')),
                ('segunda_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('segunda_seccion_destacado', models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado')),
                ('segunda_seccion_subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo')),
                ('tercera_seccion_imagen_fondo', models.ImageField(blank=True, null=True, upload_to='mypymes', verbose_name='imagen de fondo')),
                ('formulario_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título formulario')),
                ('formulario_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción formulario')),
                ('formulario_boton_principal', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón formulario')),
                ('etiqueta_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta nombre')),
                ('etiqueta_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta email')),
                ('etiqueta_telefono', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta número telefónico')),
                ('etiqueta_tipo_de_negocio', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta tipo de negocio')),
                ('tercera_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='mypymes', verbose_name='logo')),
                ('tercera_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('tercera_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('tercera_seccion_enlace', models.CharField(blank=True, max_length=255, null=True, verbose_name='enlace')),
                ('tercera_seccion_enlace_url', models.URLField(blank=True, null=True, verbose_name='url del enlace')),
                ('cuarta_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('cuarta_seccion_destacado', models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado')),
                ('quinta_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('quinta_seccion_destacado', models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado')),
                ('sexta_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='mypymes', verbose_name='imagen')),
                ('sexta_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('sexta_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('sexta_seccion_titulo_interno', models.CharField(blank=True, max_length=255, null=True, verbose_name='título interno')),
                ('sexta_seccion_subtitulo_interno', models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo interno')),
                ('sexta_seccion_primer_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='primer botón')),
                ('sexta_seccion_primer_boton_url', models.URLField(blank=True, null=True, verbose_name='url del primer botón')),
                ('sexta_seccion_segundo_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo botón')),
                ('sexta_seccion_segundo_boton_url', models.URLField(blank=True, null=True, verbose_name='url del segundo botón')),
                ('septima_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('septima_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('septima_seccion_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('septima_seccion_boton_url', models.URLField(blank=True, null=True, verbose_name='url del botón')),
                ('septima_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='mypymes', verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.AlterModelOptions(
            name='starkenpropaso',
            options={'verbose_name': 'indicaciones', 'verbose_name_plural': 'indicaciones'},
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='tercera_seccion_boton',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='tercera_seccion_boton_url',
        ),
        migrations.AddField(
            model_name='empresas',
            name='tercera_seccion_enlace',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='enlace'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='tercera_seccion_enlace_url',
            field=models.URLField(blank=True, null=True, verbose_name='url del enlace'),
        ),
        migrations.AddField(
            model_name='starkenpropaso',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Indicación'),
        ),
        migrations.CreateModel(
            name='MypymesTestimonios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('testimonio', models.TextField(blank=True, null=True, verbose_name='testimonio')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido')),
                ('puesto_laboral', models.CharField(blank=True, max_length=255, null=True, verbose_name='Puesto Laboral')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mypymes', verbose_name='Imagen de Perfil')),
                ('mypymes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.mypymes', verbose_name='Mypymes')),
            ],
            options={
                'verbose_name': 'Testimonios',
                'verbose_name_plural': 'Testimonios',
            },
        ),
        migrations.CreateModel(
            name='MypymesIndicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Número de Indicación')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('mypymes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.mypymes', verbose_name='Mypymes')),
            ],
            options={
                'verbose_name': 'indicaciones',
                'verbose_name_plural': 'indicaciones',
            },
        ),
        migrations.CreateModel(
            name='MypymesBeneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mypymes', verbose_name='ícono')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('beneficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.mypymes', verbose_name='Beneficio')),
            ],
            options={
                'verbose_name': 'Beneficios',
                'verbose_name_plural': 'Beneficios',
            },
        ),
    ]
