# Generated by Django 3.2.15 on 2022-10-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20221005_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntasfrecuentes',
            name='segunda_seccion_categoria',
        ),
        migrations.AddField(
            model_name='preguntasfrecuentes',
            name='segunda_seccion_preguntas',
            field=models.ManyToManyField(blank=True, to='cms.Preguntas', verbose_name='Preguntas'),
        ),
    ]
