# Generated by Django 3.2.15 on 2022-10-03 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_rename_fisrt_section_message_starkenpro_first_section_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('form_title_contact', models.CharField(max_length=255, verbose_name='título_contact')),
                ('form_description_contact', models.TextField(blank=True, verbose_name='descripción_contact')),
                ('form_main_button_contact', models.CharField(max_length=255, verbose_name='botón_contact')),
                ('label_name_contact', models.CharField(max_length=255, verbose_name='nombre_contact')),
                ('label_email_contact', models.CharField(max_length=255, verbose_name='email_contact')),
                ('label_phone_contact', models.CharField(max_length=255, verbose_name='phone_contact')),
                ('label_business_type_contact', models.CharField(max_length=255, verbose_name='business_type_contact')),
                ('label_message_contact', models.CharField(max_length=255, verbose_name='mensaje_contact')),
                ('second_section_title', models.CharField(max_length=255, verbose_name='título')),
                ('second_section_highlight', models.CharField(max_length=255, verbose_name='destacado')),
                ('second_section_description', models.TextField(blank=True, verbose_name='descripción')),
                ('third_section_title', models.CharField(max_length=255, verbose_name='título')),
                ('third_section_highlight', models.CharField(max_length=255, verbose_name='destacado')),
                ('third_section_description', models.TextField(blank=True, verbose_name='descripción')),
                ('third_section_main_button', models.CharField(max_length=255, verbose_name='botón')),
                ('third_section_main_button_url', models.URLField(verbose_name='url del botón')),
                ('form_title', models.CharField(max_length=255, verbose_name='título')),
                ('form_description', models.TextField(blank=True, verbose_name='descripción')),
                ('form_main_button', models.CharField(max_length=255, verbose_name='botón')),
                ('label_name', models.CharField(max_length=255, verbose_name='nombre')),
                ('label_email', models.CharField(max_length=255, verbose_name='email')),
                ('label_message', models.CharField(max_length=255, verbose_name='mensaje')),
                ('fourth_section_image', models.ImageField(upload_to='helpcenter', verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'centro de ayuda',
                'verbose_name_plural': 'centros de ayuda',
            },
        ),
        migrations.CreateModel(
            name='HelpCenterQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('quetion', models.CharField(max_length=255, verbose_name='question')),
                ('answers', models.TextField(blank=True, verbose_name='answers')),
                ('help_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.helpcenter', verbose_name='Help Center')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
            },
        ),
        migrations.CreateModel(
            name='HelpCenterBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('image', models.ImageField(upload_to='help_center', verbose_name='imagen')),
                ('help_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.helpcenter', verbose_name='Help Center')),
            ],
            options={
                'verbose_name': 'beneficio',
                'verbose_name_plural': 'beneficios',
            },
        ),
    ]
