# Generated by Django 3.2.15 on 2022-10-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20221007_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypymes',
            options={'verbose_name': 'MYPYMES', 'verbose_name_plural': 'MYPYMES'},
        ),
        migrations.RemoveField(
            model_name='mypymestestimonios',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='mypymestestimonios',
            name='titulo',
        ),
    ]
