# Generated by Django 3.2.15 on 2022-10-03 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_helpcenter_helpcenterbenefit_helpcenterquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsofService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'Condición de Servicio',
                'verbose_name_plural': 'Condiciones de Servicio',
            },
        ),
        migrations.RemoveField(
            model_name='helpcenterquestion',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='helpcenterquestion',
            name='quetion',
        ),
        migrations.CreateModel(
            name='TermsofServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('terms_of_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.termsofservice', verbose_name='Terms of Service')),
            ],
            options={
                'verbose_name': 'Punto de Condición de Servicio',
                'verbose_name_plural': 'Puntos de Condiciones de Servicio',
            },
        ),
    ]
