# Generated by Django 3.2.15 on 2022-10-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20221005_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntascategoria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='preguntascategoria',
            name='titulo',
        ),
        migrations.AddField(
            model_name='about',
            name='primera_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='about',
            name='primera_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='about',
            name='quinta_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='about',
            name='quinta_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='primera_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='primera_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='segunda_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='segunda_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='banner',
            name='alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='banner',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='cuarta_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='cuarta_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='centrodeayudabeneficio',
            name='alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='centrodeayudabeneficio',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='tercera_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='tercera_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='datos',
            name='alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='datos',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='home',
            name='cuarta_seccion_tarjeta_1_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='home',
            name='cuarta_seccion_tarjeta_1_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='home',
            name='cuarta_seccion_tarjeta_2_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='home',
            name='cuarta_seccion_tarjeta_2_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='home',
            name='primera_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='home',
            name='primera_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='iconos',
            name='alt_icono',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt ícono'),
        ),
        migrations.AddField(
            model_name='iconos',
            name='titulo_icono',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título ícono'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='starkenpro',
            name='primera_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='starkenpro',
            name='primera_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='starkenprobeneficio',
            name='alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='starkenprobeneficio',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='primera_descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='primera descripción'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='segunda_descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='segunda descripción'),
        ),
        migrations.AlterField(
            model_name='iconos',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='iconos', verbose_name='ícono'),
        ),
    ]
