# Generated by Django 3.2.15 on 2022-10-07 22:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20221007_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypymesindicaciones',
            name='number',
        ),
        migrations.RemoveField(
            model_name='starkenpropaso',
            name='number',
        ),
        migrations.AddField(
            model_name='enviosnacionalesrecomendaciones',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='primera_seccion_miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='mypymes', verbose_name='imagen miniatura'),
        ),
        migrations.AlterField(
            model_name='miprimerenviostep',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='mypymes',
            name='primera_seccion_video',
            field=models.URLField(blank=True, null=True, verbose_name='video'),
        ),
    ]
