# Generated by Django 3.2.15 on 2022-10-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20221006_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminosdeservicioseccion',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='id'),
        ),
    ]
