# Generated by Django 3.2.15 on 2022-10-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20221007_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='mypymes', verbose_name='imagen')),
                ('primera_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('primera_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('primera_seccion_boton_url', models.URLField(blank=True, null=True, verbose_name='url del botón')),
                ('formulario_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título formulario')),
                ('formulario_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción formulario')),
                ('formulario_boton_principal', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón formulario')),
                ('etiqueta_rut', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta RUT')),
                ('etiqueta_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta nombre')),
                ('etiqueta_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta email')),
                ('etiqueta_telefono', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta número telefónico')),
                ('etiqueta_reclamo', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta reclamo')),
                ('tercera_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('tercera_seccion_subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo')),
                ('tercera_seccion_destacado', models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado')),
                ('tercera_seccion_enlace_url', models.URLField(blank=True, null=True, verbose_name='url del enlace')),
                ('tercera_seccion_preguntas', models.ManyToManyField(blank=True, to='cms.Preguntas', verbose_name='Preguntas')),
            ],
            options={
                'verbose_name': 'Reclamos',
                'verbose_name_plural': 'Reclamos',
            },
        ),
    ]
