# Generated by Django 3.2.15 on 2022-10-10 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_reclamos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primera_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='recomendaciones', verbose_name='imagen')),
                ('pregunta_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='pregunta título')),
                ('pregunta_descripcion', models.TextField(blank=True, null=True, verbose_name='pregunta descripción')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
            },
        ),
        migrations.CreateModel(
            name='RecomendacionesCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_categoria', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título de categoría')),
            ],
            options={
                'verbose_name': 'Recomendaciones - Categoría',
                'verbose_name_plural': 'Recomendaciones - Categoría',
            },
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='primera_seccion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='reclamos', verbose_name='imagen'),
        ),
        migrations.CreateModel(
            name='RecomendacionesEmbalaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='recomendaciones de embalaje', verbose_name='imagen de fondo')),
                ('primera_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('primera_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('primera_seccion_boton_url', models.URLField(blank=True, null=True, verbose_name='url del botón')),
                ('segunda_seccion_recomendaciones', models.ManyToManyField(blank=True, to='cms.Recomendaciones', verbose_name='Recomendaciones')),
            ],
            options={
                'verbose_name': 'Recomendaciones de Embalaje',
                'verbose_name_plural': 'Recomendaciones de Embalaje',
            },
        ),
        migrations.AddField(
            model_name='recomendaciones',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='cms.recomendacionescategoria', verbose_name='Recomendaciones'),
        ),
    ]
