# Generated by Django 3.2.15 on 2022-10-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20221010_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendaciones',
            old_name='pregunta_descripcion',
            new_name='recomendación_descripcion',
        ),
        migrations.AddField(
            model_name='recomendacionescategoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='recomendacionescategoria',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='recomendaciones',
            name='pregunta_titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='recomendación título'),
        ),
    ]
