# Generated by Django 3.2.15 on 2022-10-10 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20221010_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primera_seccion_titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('primera_seccion_alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('primera_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='seguimiento', verbose_name='imagen de fondo')),
                ('primera_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('primera_seccion_subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo')),
                ('segunda_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('segunda_seccion_subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='subtítulo')),
                ('segunda_seccion_boton_principal', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón formulario')),
                ('segunda_seccion_etiqueta_codigo', models.CharField(blank=True, max_length=255, null=True, verbose_name='etiqueta código')),
                ('tercera_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('tercera_seccion_destacado', models.CharField(blank=True, max_length=255, null=True, verbose_name='destacado')),
                ('tercera_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('cuarta_seccion_tarjeta_1_titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('cuarta_seccion_tarjeta_1_alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('cuarta_seccion_tarjeta_1_imagen', models.ImageField(blank=True, null=True, upload_to='home', verbose_name='imagen')),
                ('cuarta_seccion_tarjeta_1_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('cuarta_seccion_tarjeta_1_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('cuarta_seccion_tarjeta_1_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('cuarta_seccion_tarjeta_1_boton_url', models.URLField(blank=True, null=True, verbose_name='url del botón')),
                ('cuarta_seccion_tarjeta_2_titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('cuarta_seccion_tarjeta_2_alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('cuarta_seccion_tarjeta_2_imagen', models.ImageField(blank=True, null=True, upload_to='home', verbose_name='imagen')),
                ('cuarta_seccion_tarjeta_2_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('cuarta_seccion_tarjeta_2_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('cuarta_seccion_tarjeta_2_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('cuarta_seccion_tarjeta_2_boton_url', models.URLField(blank=True, null=True, verbose_name='url del botón')),
                ('quinta_seccion_titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('quinta_seccion_alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('quinta_seccion_imagen', models.ImageField(blank=True, null=True, upload_to='seguimiento', verbose_name='imagen')),
                ('quinta_seccion_titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('quinta_seccion_palabras', models.CharField(blank=True, help_text='separadas por coma', max_length=255, null=True, verbose_name='palabras')),
                ('quinta_seccion_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('quinta_seccion_boton_principal', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('quinta_seccion_boton_principal_url', models.URLField(blank=True, null=True, verbose_name='url del botón')),
            ],
            options={
                'verbose_name': 'Seguimiento de Envío',
                'verbose_name_plural': 'Seguimiento de Envío',
            },
        ),
        migrations.RenameField(
            model_name='recomendaciones',
            old_name='pregunta',
            new_name='recomendacion',
        ),
        migrations.AddField(
            model_name='accion',
            name='alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='accion',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='dhl',
            name='primera_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='dhl',
            name='primera_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='cuarta_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='cuarta_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='primera_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='primera_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='quinta_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='quinta_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='tercera_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='tercera_seccion_alt_imagen_fondo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen de fondo'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='tercera_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='tercera_seccion_titulo_imagen_fondo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen de fondo'),
        ),
        migrations.AddField(
            model_name='empresasbeneficios',
            name='alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='empresasbeneficios',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='empresascarrusel',
            name='alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='empresascarrusel',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='cuarta_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='cuarta_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='primera_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='primera_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='quinta_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='quinta_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='tercera_seccion_alt_imagen_primer_bloque',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='tercera_seccion_alt_imagen_segundo_bloque',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='tercera_seccion_titulo_imagen_primer_bloque',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen primer bloque'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='tercera_seccion_titulo_imagen_segundo_bloque',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen segundo bloque'),
        ),
        migrations.AddField(
            model_name='enviosinternacionalesbeneficios',
            name='alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='enviosinternacionalesbeneficios',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='enviosnacionales',
            name='cuarta_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='enviosnacionales',
            name='cuarta_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='enviosnacionales',
            name='primera_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='enviosnacionales',
            name='primera_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='enviosnacionales',
            name='tercera_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='enviosnacionales',
            name='tercera_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='enviosnacionalesbeneficios',
            name='alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='enviosnacionalesbeneficios',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='enviosnacionalesrecomendaciones',
            name='alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='enviosnacionalesrecomendaciones',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='miprimerenvio',
            name='primera_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='miprimerenvio',
            name='primera_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='miprimerenviostep',
            name='alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='miprimerenviostep',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='modalidades',
            name='alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='modalidades',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='primera_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='primera_seccion_alt_imagen_miniatura',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen miniatura'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='primera_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='primera_seccion_titulo_imagen_miniatura',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen miniatura'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='septima_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='septima_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='sexta_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='sexta_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='tercera_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='tercera_seccion_alt_imagen_fondo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen de fondo'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='tercera_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='tercera_seccion_titulo_imagen_fondo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen de fondo'),
        ),
        migrations.AddField(
            model_name='mypymesbeneficios',
            name='alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='mypymesbeneficios',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='mypymestestimonios',
            name='alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='mypymestestimonios',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='primera_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='primera_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='recomendaciones',
            name='alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='recomendaciones',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.AddField(
            model_name='recomendacionesembalaje',
            name='primera_seccion_alt_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='recomendacionesembalaje',
            name='primera_seccion_titulo_imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen'),
        ),
        migrations.CreateModel(
            name='SeguimientoIndicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='seguimiento', verbose_name='imagen')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('enlace', models.CharField(blank=True, max_length=255, null=True, verbose_name='enlace')),
                ('enlace_url', models.URLField(blank=True, null=True, verbose_name='url del enlace')),
                ('seguimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.seguimiento', verbose_name='Seguimiento')),
            ],
            options={
                'verbose_name': 'Indicaciones',
                'verbose_name_plural': 'Indicaciones',
            },
        ),
    ]
