# Generated by Django 3.2.16 on 2022-10-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20221013_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='alt_imagen_movil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen móvil'),
        ),
        migrations.AddField(
            model_name='banner',
            name='imagen_movil',
            field=models.ImageField(blank=True, null=True, upload_to='carousel', verbose_name='imagen móvil'),
        ),
        migrations.AddField(
            model_name='banner',
            name='titulo_imagen_movil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen móvil'),
        ),
    ]
