# Generated by Django 3.2.16 on 2022-10-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_auto_20221014_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodeayuda',
            name='cuarta_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='primera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='segunda_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='centrodeayuda',
            name='tercera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='primera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='contactanos',
            name='tercera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='primera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='segunda_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='covid',
            name='primera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='dhl',
            name='cuarta_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='dhl',
            name='primera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='dhl',
            name='segunda_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='dhl',
            name='tercera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='cuarta_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='primera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='quinta_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='segunda_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='tercera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='cuarta_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='primera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='quinta_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='segunda_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='enviosinternacionales',
            name='tercera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='enviosnacionales',
            name='cuarta_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='enviosnacionales',
            name='primera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='enviosnacionales',
            name='segunda_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='enviosnacionales',
            name='tercera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='miprimerenvio',
            name='primera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='cuarta_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='primera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='quinta_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='segunda_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='septima_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='sexta_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='mypymes',
            name='tercera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='primera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='segunda_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='reclamos',
            name='tercera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='recomendacionesembalaje',
            name='primera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='cuarta_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='primera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='segunda_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='tercera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='primera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='terminosdeservicio',
            name='primera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='terminosdeservicio',
            name='segunda_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
        migrations.AddField(
            model_name='terminosdeservicio',
            name='tercera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
    ]
