# Generated by Django 3.2.16 on 2022-10-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20221014_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacionescategoria',
            name='primera_seccion_ocultar',
            field=models.BooleanField(default=False, verbose_name='Ocultar'),
        ),
    ]
