# Generated by Django 3.2.16 on 2022-10-14 17:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_recomendacionescategoria_primera_seccion_ocultar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='primera_seccion_fecha',
        ),
        migrations.AddField(
            model_name='covid',
            name='primera_seccion_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='covidcomunicado',
            name='primera_seccion_contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='contenido'),
        ),
    ]
