# Generated by Django 3.2.16 on 2022-11-24 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0002_auto_20221123_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='titulo')),
                ('destacado', models.CharField(blank=True, max_length=200, null=True, verbose_name='destacado')),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='destacado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primer_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='primer botón')),
                ('segundo_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo botón')),
                ('titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='banner_seccion', verbose_name='imagen')),
                ('titulo_imagen_movil', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen móvil')),
                ('alt_imagen_movil', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen móvil')),
                ('imagen_movil', models.ImageField(blank=True, null=True, upload_to='banner_seccion', verbose_name='imagen móvil')),
                ('primer_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_primer_boton_banner', to='cms.url', verbose_name='url del primer botón')),
                ('segundo_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_segundo_boton_banner', to='cms.url', verbose_name='url del segundo botón')),
            ],
        ),
        migrations.CreateModel(
            name='BasicoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='titulo')),
                ('destacado', models.CharField(blank=True, max_length=200, null=True, verbose_name='destacado')),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='destacado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primer_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='primer botón')),
                ('segundo_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo botón')),
                ('titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='basico_seccion', verbose_name='imagen')),
                ('invertir_sentido', models.BooleanField(default=False, verbose_name='invertir sentido')),
                ('primer_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_primer_boton_basico', to='cms.url', verbose_name='url del primer botón')),
                ('segundo_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_segundo_boton_basico', to='cms.url', verbose_name='url del segundo botón')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficioSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BloquesSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_bloque_titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='titulo primer bloque')),
                ('primer_bloque_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción primer bloque')),
                ('primer_bloque_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='primer botón')),
                ('primer_bloque_titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen primer bloque')),
                ('primer_bloque_alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen primer bloque')),
                ('primer_bloque_imagen', models.ImageField(blank=True, null=True, upload_to='bloques_seccion', verbose_name='imagen primer bloque')),
                ('segundo_bloque_titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='titulo segundo bloque')),
                ('segundo_bloque_descripcion', models.TextField(blank=True, null=True, verbose_name='descripción segundo bloque')),
                ('segundo_bloque_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo botón')),
                ('segundo_bloque_titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen segundo bloque')),
                ('segundo_bloque_alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen segundo bloque')),
                ('segundo_bloque_imagen', models.ImageField(blank=True, null=True, upload_to='bloques_seccion', verbose_name='imagen segundo bloque')),
                ('primer_bloque_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_primer_bloque_boton', to='cms.url', verbose_name='url del primer botón')),
                ('segundo_bloque_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_segundo_bloque_boton', to='cms.url', verbose_name='url del segundo botón')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('header', models.BooleanField(default=False)),
                ('footer', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='titulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicio_seccion', verbose_name='imagen')),
                ('boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_boton_servicios_pages', to='cms.url', verbose_name='url del primer botón')),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='titulo')),
                ('destacado', models.CharField(blank=True, max_length=200, null=True, verbose_name='destacado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primer_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='primer botón')),
                ('segundo_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo botón')),
                ('primer_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_primer_boton_servicios_pages', to='cms.url', verbose_name='url del primer botón')),
                ('segundo_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_segundo_boton_servicios_pages', to='cms.url', verbose_name='url del segundo botón')),
                ('servicios', models.ManyToManyField(blank=True, to='pages.Servicio', verbose_name='servicios')),
            ],
        ),
        migrations.CreateModel(
            name='PageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Banner Seccion'), (2, 'Beneficio Seccion'), (3, 'Basico Seccion'), (4, 'Servicios Seccion'), (5, 'Bloques Seccion')])),
                ('banner_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.bannerseccion')),
                ('basico_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.basicoseccion')),
                ('beneficio_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.beneficioseccion')),
                ('bloques_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.bloquesseccion')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.page')),
                ('servicios_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.serviciosseccion')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='beneficio_seccion', verbose_name='imagen')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='pages.beneficioseccion')),
            ],
        ),
    ]
