# Generated by Django 3.2.16 on 2023-01-06 18:15

from django.db import migrations, models
import django.db.models.deletion
import faicon.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='titulo')),
                ('destacado', models.CharField(blank=True, max_length=200, null=True, verbose_name='destacado')),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='subtítulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primer_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='primer botón')),
                ('primer_boton_icono', faicon.fields.FAIconField(blank=True, max_length=50, null=True, verbose_name='ícono primer botón')),
                ('segundo_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo botón')),
                ('segundo_boton_icono', faicon.fields.FAIconField(blank=True, max_length=50, null=True, verbose_name='ícono segundo botón')),
                ('titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='banner_seccion', verbose_name='imagen')),
                ('titulo_imagen_movil', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen móvil')),
                ('alt_imagen_movil', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen móvil')),
                ('imagen_movil', models.ImageField(blank=True, null=True, upload_to='banner_seccion', verbose_name='imagen móvil')),
                ('primer_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_primer_boton_banner', to='cms.url', verbose_name='url del primer botón')),
                ('segundo_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_segundo_boton_banner', to='cms.url', verbose_name='url del segundo botón')),
            ],
        ),
        migrations.CreateModel(
            name='BasicoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='titulo')),
                ('destacado', models.CharField(blank=True, max_length=200, null=True, verbose_name='destacado')),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='subtítulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primer_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='primer botón')),
                ('primer_boton_icono', faicon.fields.FAIconField(blank=True, max_length=50, null=True, verbose_name='ícono primer botón')),
                ('segundo_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo botón')),
                ('segundo_boton_icono', faicon.fields.FAIconField(blank=True, max_length=50, null=True, verbose_name='ícono segundo botón')),
                ('titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='basico_seccion', verbose_name='imagen')),
                ('invertir_sentido', models.IntegerField(blank=True, choices=[(0, 'IMAGEN A LA IZQUIERDA'), (1, 'IMAGEN A LA DERECHA')], default=1, null=True, verbose_name='Posición de la Imagen')),
                ('primer_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_primer_boton_basico', to='cms.url', verbose_name='url del primer botón')),
                ('segundo_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_segundo_boton_basico', to='cms.url', verbose_name='url del segundo botón')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='beneficio_seccion', verbose_name='imagen')),
                ('boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='primer botón')),
                ('boton_icono', faicon.fields.FAIconField(blank=True, max_length=50, null=True, verbose_name='ícono botón')),
                ('boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_boton_beneficio', to='cms.url', verbose_name='url del botón')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficioSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('beneficios', models.ManyToManyField(blank=True, to='pages.Beneficio', verbose_name='Beneficios')),
            ],
        ),
        migrations.CreateModel(
            name='Bloques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='titulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('boton_icono', faicon.fields.FAIconField(blank=True, max_length=50, null=True, verbose_name='ícono botón')),
                ('titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bloques_seccion', verbose_name='imagen')),
                ('boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_boton_bloque', to='cms.url', verbose_name='url del botón')),
            ],
        ),
        migrations.CreateModel(
            name='BloquesSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='titulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('bloques', models.ManyToManyField(blank=True, to='pages.Bloques', verbose_name='Bloques')),
            ],
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Text'), (2, 'Textarea'), (3, 'Number'), (4, 'Boolean'), (5, 'Date'), (6, 'Time'), (7, 'File')])),
                ('label', models.CharField(blank=True, max_length=200, null=True, verbose_name='label')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='FormularioSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulario', to='pages.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('header', models.BooleanField(default=False)),
                ('footer', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='fecha de creación')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='titulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='botón')),
                ('boton_icono', faicon.fields.FAIconField(blank=True, max_length=50, null=True, verbose_name='ícono botón')),
                ('titulo_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='título imagen')),
                ('alt_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicio_seccion', verbose_name='imagen')),
                ('boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_boton_servicios_pages', to='cms.url', verbose_name='url del primer botón')),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='titulo')),
                ('destacado', models.CharField(blank=True, max_length=200, null=True, verbose_name='destacado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('primer_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='primer botón')),
                ('primer_boton_icono', faicon.fields.FAIconField(blank=True, max_length=50, null=True, verbose_name='ícono primer botón')),
                ('segundo_boton', models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo botón')),
                ('segundo_boton_icono', faicon.fields.FAIconField(blank=True, max_length=50, null=True, verbose_name='ícono segundo botón')),
                ('primer_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_primer_boton_servicios_pages', to='cms.url', verbose_name='url del primer botón')),
                ('segundo_boton_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_segundo_boton_servicios_pages', to='cms.url', verbose_name='url del segundo botón')),
                ('servicios', models.ManyToManyField(blank=True, to='pages.Servicio', verbose_name='Servicios')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=200, null=True, verbose_name='valor')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.campo', verbose_name='campo')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pages.resultado')),
            ],
        ),
        migrations.CreateModel(
            name='PageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Banner Seccion'), (2, 'Beneficio Seccion'), (3, 'Basico Seccion'), (4, 'Servicios Seccion'), (5, 'Bloques Seccion'), (6, 'Formulario Seccion')])),
                ('banner_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.bannerseccion')),
                ('basico_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.basicoseccion')),
                ('beneficio_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.beneficioseccion')),
                ('bloques_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.bloquesseccion')),
                ('formulario_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.formularioseccion')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.page')),
                ('servicios_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.serviciosseccion')),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.opciongrupo')),
            ],
        ),
        migrations.CreateModel(
            name='EtiquetasMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('content', models.CharField(max_length=200, verbose_name='content')),
                ('property', models.CharField(blank=True, max_length=200, null=True, verbose_name='property')),
                ('itemprop', models.CharField(blank=True, max_length=200, null=True, verbose_name='itemprop')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.page')),
            ],
        ),
        migrations.AddField(
            model_name='campo',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.formulario'),
        ),
        migrations.AddField(
            model_name='campo',
            name='opciones',
            field=models.ManyToManyField(blank=True, to='pages.Opcion'),
        ),
    ]
