# Generated by Django 3.2.16 on 2023-01-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20230120_1038'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerseccion',
            name='primer_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_primer_boton_banner', to='cms.url', verbose_name='url del primer botón'),
        ),
        migrations.AlterField(
            model_name='bannerseccion',
            name='segundo_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_segundo_boton_banner', to='cms.url', verbose_name='url del segundo botón'),
        ),
        migrations.AlterField(
            model_name='basicoseccion',
            name='primer_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_primer_boton_basico', to='cms.url', verbose_name='url del primer botón'),
        ),
        migrations.AlterField(
            model_name='basicoseccion',
            name='segundo_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_segundo_boton_basico', to='cms.url', verbose_name='url del segundo botón'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_beneficio', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='beneficioseccion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficioseccion',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bloques',
            name='boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_bloque', to='cms.url', verbose_name='url del botón'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Text'), (2, 'Textarea'), (3, 'Number'), (4, 'Boolean'), (5, 'Date'), (6, 'Time'), (7, 'File')], null=True),
        ),
        migrations.AlterField(
            model_name='etiquetasmeta',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='formularioseccion',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario', to='pages.formulario'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.opciongrupo'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='page',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagedetail',
            name='banner_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.bannerseccion'),
        ),
        migrations.AlterField(
            model_name='pagedetail',
            name='basico_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.basicoseccion'),
        ),
        migrations.AlterField(
            model_name='pagedetail',
            name='beneficio_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.beneficioseccion'),
        ),
        migrations.AlterField(
            model_name='pagedetail',
            name='bloques_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.bloquesseccion'),
        ),
        migrations.AlterField(
            model_name='pagedetail',
            name='formulario_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.formularioseccion'),
        ),
        migrations.AlterField(
            model_name='pagedetail',
            name='servicios_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.serviciosseccion'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.formulario'),
        ),
        migrations.AlterField(
            model_name='resultadodetalle',
            name='campo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.campo', verbose_name='campo'),
        ),
        migrations.AlterField(
            model_name='resultadodetalle',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pages.resultado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_boton_servicios_pages', to='cms.url', verbose_name='url del primer botón'),
        ),
        migrations.AlterField(
            model_name='serviciosseccion',
            name='primer_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_primer_boton_servicios_pages', to='cms.url', verbose_name='url del primer botón'),
        ),
        migrations.AlterField(
            model_name='serviciosseccion',
            name='segundo_boton_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_segundo_boton_servicios_pages', to='cms.url', verbose_name='url del segundo botón'),
        ),
    ]
